### ISSUE TITLE
Clean documentation

### ISSUE THREAD

**Issue by jared321** [bandframework/Taweret#114] opened 2024-09-17 13:16 UTC
Need to polish the sphinx-based docs prior to release.

**Comment by asemposki** [comment] 2024-09-18 02:38
@jared321 To the conditional vs. conditioned question, the second instance of its use is the one that indicated to me that we indeed meant 'conditional', since the weights of the model are conditional on the model predictions in some cases. It's from the Bayes conditional posterior idea. 

To the documentation, I do not know what to put there, either---I think it was intended for us to note how that will be updated, but I don't think that it is something crucial to have down for this release.

I've attempted to fix most of the docstring issues above.

**Comment by asemposki** [comment] 2024-09-19 13:23
OK the PR has been merged and everything looks good, so I'll close this.

**Closed by asemposki** 2024-09-19 13:23 UTC
